<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 2                     */
/* CACHE FILE: Generated: Wed, 28 Jul 2004 10:38:07 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY     $vsLang->currentLang->getFoldername()       */
/*--------------------------------------------------*/

class skin_global {

	function vs_global(){
        global $bw, $vsLang, $vsMenu, $vsSettings, $urlcate, $vsPrint;

				$count= count($_SESSION [$_SESSION [APPLICATION_TYPE]['language']['currentLang']['langFolder']] ['cart'] ['item'])?count($_SESSION [$_SESSION [APPLICATION_TYPE]['language']['currentLang']['langFolder']] ['cart'] ['item']):'0';

		$BWHTML .= <<<EOF
    <!-- <script type="text/javascript" src="https://apis.google.com/js/plusone.js">{lang: 'vi'}</script> -->
    <div class="container top-container">
    <div class="container-fluid logo_header no-padding">
        <a href="{$bw->base_url}" class="logo"><img src="{$bw->vars['img_url']}/logo.jpg" /></a>
        <div class="order">
            <div class="giohang_2"><span>Giỏ hàng: [{$count}]</span></div>
            <a href="{$bw->base_url}orders"><div class="dathang"><span>Đặt hàng</span></div></a>
						<a href="{$bw->base_url}payment"><div class="payment"><span>Thanh toán</span></div></a>
        </div>
    </div>
    <div class="container-fluid no-padding menu-full" style="position:relative">
        <div class="wrap_form_search">{$this->search}</div>
        {$this->menu}
    </div>
    <div class="container-fluid no-padding">
        <div class="option">
            <div class="link_home">
            {$this->navigator}
            </div>
            <div class="support pull-right">
                <h3>Hỗ trợ trực tuyến:</h3>
                <foreach="$this->portlet_supports as $supp">
                    {$supp->show()}
                </foreach>
            </div>
        </div>
    </div>
	<if=" !$bw->isMobile ">
    <div class="container-fluid no-padding slide_top_full">
        <div id="slide_top">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 no-padding" >
                <div id="slider" class="nivoSlider">
                   <foreach="$this->wl['banner'] as $obj">
                       {$obj->createImageCache($obj->getImage(), 938, 310, 1, 0, $obj->getTitle())}
                   </foreach>
               </div>
			   <div class="hotline">Hotline:<span>{$vsSettings->getSystemKey("global_hotline","0","config")}</span></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
	<else />
		<div class="container-fluid no-padding slide_top_full">
			<div class='hotline-button'>
		Hotline:<span>{$vsSettings->getSystemKey("global_hotline","0","config")}</span>
		</div>
		</div>
	</if>

<if="$bw->input['module']==contacts ">
    <div class="content container-fluid no-padding" >
        {$this->SITE_MAIN_CONTENT}
    </div>
<else />
    <div class="content container-fluid no-padding">
		<if=" !$bw->isMobile ">
        <div class="sidebar_left col-lg-3 col-md-4 col-sm-6 col-xs-12">
            <div class="cate_left cate_left_top">
                <div class="main_cate_left">
                    <ul class="cate_top" id="menu">
                        <foreach="$this->cateproducts as $obj">
                            <li><a href="{$obj->getUrlCategory('cateproducts')}">{$obj->getTitle()}</a></li>
                        </foreach>
                    </ul>
                </div>
            </div><!--cate_left-->
            <div class="cate_left cate_left_2">
                <div class="main_cate_left">
                    <h3>Quà tặng</h3>
                    <ul class="cate_2">
                        <foreach="$this->catequatang as $obj">
                            <li><a href="{$obj->getUrlCategory('catequatang')}">{$obj->getTitle()}</a></li>
                        </foreach>
                    </ul>
                </div>
            </div><!--cate_left-->
            <div class="cate_left cate_left_2">
                <div class="main_cate_left">
                    <h3>Liên kết banner</h3>
                    <foreach="$this->wl['khang'] as $obj">
                        <a title="{$obj->getTitle()}" href="{$obj->getWebsite()}" target= "_blank">{$obj->createImageCache($obj->getImage(),212,344,5,0,$obj->getTitle())}</a>
                    </foreach>
                </div>
            </div><!--cate_left-->
        </div><!--sidebar-->
		</if>
        <div class="primary1 col-lg-9 col-md-9 col-sm-12 col-xs-12">
            <div class="item_home">
                <if="$bw->input['module']==orders "> <div class="div_orders" style="width:100%"></if>
                {$this->SITE_MAIN_CONTENT}

                <if="$bw->input['module']==orders "> </div "></if>
                <if=" !$bw->isMobile && ($bw->input['module']==home || $bw->input['module']==abouts)">
                    {$this->addVideo($this->wl['videos'])}
                </if>
            </div>
        </div><!--primary-->
        <div class="clear"></div>
		<if=" $bw->isMobile ">
				<div class="sidebar_left col-lg-3 col-md-3 col-sm-12 col-xs-12">
            <div class="cate_left cate_left_top">
                <div class="main_cate_left">
                    <ul class="cate_top"  id="menu">
                        <foreach="$this->cateproducts as $obj">
                            <li><a href="{$obj->getUrlCategory('cateproducts')}">{$obj->getTitle()}</a></li>
                        </foreach>
                    </ul>
                </div>
            </div><!--cate_left-->
            <div class="cate_left cate_left_2">
                <div class="main_cate_left">
                    <h3>Quà tặng</h3>
                    <ul class="cate_2">
                        <foreach="$this->catequatang as $obj">
                            <li><a href="{$obj->getUrlCategory('catequatang')}">{$obj->getTitle()}</a></li>
                        </foreach>
                    </ul>
                </div>
            </div><!--cate_left-->
            <div class="cate_left cate_left_2">
                <div class="main_cate_left">
                    <h3>Liên kết banner</h3>
                    <foreach="$this->wl['khang'] as $obj">
                        <a title="{$obj->getTitle()}" href="{$obj->getWebsite()}" target= "_blank">{$obj->createImageCache($obj->getImage(),212,344,5,0,$obj->getTitle())}</a>
                    </foreach>
                </div>
            </div><!--cate_left-->
        </div><!--sidebar-->
		</if>
    </div><!--enc content-->
		<div class="menu_bot">

				{$this->menu_footer}
				<div id="top" class="back_top">Lên trên cùng</div>
		</div>
</if>
    <div class="footer">
        <div class="main_footer">
            <div style="float: left; padding:15px 10px; color:#fff;">
                {$this->contacts->getIntro()}
                <p style="width:100%"><span><a style="color:#FFF;" href="http://www.vietsol.net">Thiết kế web</a> bởi <a href='http://www.vietsol.net/gioi-thieu-cong-ty-thiet-ke-web/' target='_blank' title='Công ty thiết kế web'>Viet Solution</a></span></p>
            </div>

            <div class="weblinks col-lg-3 col-md-6 col-sm-12 col-xs-12">
                <div class="social">
                        <a href="$facebook" target="_blank"><i class="zmdi zmdi-hc-2x zmdi-facebook"></i></a>
                        <a href="$google" target="_blank"><i class="zmdi zmdi-hc-2x zmdi-google-plus"></i></a>
                        <a href="$youtube" target="_blank"><i class="zmdi zmdi-hc-2x zmdi-youtube"></i></a>
                </div>
             	<div class="weblink">
                    <h3>Liên kết web</h3>
                    {$this->portlet_dropdown_weblink}
             	</div>
                <div class="clear"></div>
                <div class="online">
                    <span><font color="#FFFFFF">{$vsLang->getWordsGlobal('global_visit2','Tổng truy cập')}:</font></span>
                    <span style="font-weight:bold">{$this->state['visits']}</span>
                    <span><font color="#FFFFFF">{$vsLang->getWordsGlobal('global_current',' - Đang online')}:</font></span>
                    <span style="font-weight:bold">{$this->state['today']}</span>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="bg_footer_bottom"></div>
<script type="text/javascript">
    $(document).ready( function(){
        $('.cate_top').find('li:first').addClass('cate_top_first');
        $('.cate_top').find('li:last').addClass('cate_top_last');
        $('.link_home').find('a:first').addClass('link_home_first');
        $(window).load(function() {
            $('#slider').nivoSlider({
                controlNav: false,
                prevText: '',
                nextText: '',
            });
        });

        $('.link_home').find('a:last').addClass('active');
        $('.primary').find('.hr:last').remove();
        $('.menu_top').find('span:last').remove();
        $('.nivo-controlNav').find('.nivo-control:last').addClass('abc');
        $('#top').click(function() {
            $('html, body').animate({scrollTop:0},500);
        });
    });

    $(document).ready(function(){
        $('.video_home .slide_it a').click(function(){
            var option = {width: 818,height:444};
            var id = $(this).attr('ref');
            vsf.popupLightGet('videos/detail_video/'+id, 'chau1233', option);
        });
    });

	(function() {
	var _h1= document.getElementsByTagName('title')[0] || false;
	var product_name = '';
	if(_h1){
	product_name= _h1.textContent || _h1.innerText;
	}
	   var ga = document.createElement('script');
	   ga.type = 'text/javascript';
	   ga.src = '//live.vnpgroup.net/js/web_client_box.php?hash=1ae250a78cad66d7adb3e77b0c49edf3&data=eyJoYXNoIjoiNzA5ODY3ZDkzMmFkOThmODZlMjdiYTg4ZjBlMTg3ZDciLCJzc29faWQiOjk0OTUyfQ--&pname='+product_name;
	   var s = document.getElementsByTagName('script');
	   s[0].parentNode.insertBefore(ga, s[0]);
	})();
</script>


EOF;

    return $BWHTML;

	}

function addVideo($list = array()) {
    global $bw,$vsLang;
		$BWHTML .= <<<EOF
<h3 class="title_cate">Video</h3>
                    <div class="main_item main_video" >
                        <div id="video_home" class="video_home owl-carousel owl-theme">
                            <foreach="$list as $obj">
                                <div class="slide_it">
                                    <a ref='{$obj->getId()}'>
                                        <img class="img_full" src="http://img.youtube.com/vi/{$obj->getAddress()}/2.jpg" />
                                    </a>
                                </div>
                            </foreach>
                        </div>
                    </div>
    <script>
    $(document).ready(function() {
      var owl = $(".video_home");
      owl.owlCarousel({
            itemsCustom : [
                [0, 1],
                [450, 1],
                [600, 1],
                [700, 1],
                [1000, 2],
                [1200, 4],
                [1400, 4],
                [1600, 4]
            ],
            navigation : true,
            navigationText: [
                "<img src='{$bw->vars['img_url']}/owl-prev.jpg'>",
                "<img src='{$bw->vars['img_url']}/owl-next.jpg'>"
            ],
      });
    });
    </script>
EOF;
		//--endhtml--//
		return $BWHTML;
	}
function addCSS($cssUrl="") {
		$BWHTML .= <<<EOF
<link type="text/css" rel="stylesheet" href="{$cssUrl}.css" />
EOF;
		//--endhtml--//
		return $BWHTML;
	}
	function importantAjaxCallBack(){
		global $bw,$vsLang;
		$BWHTML .= <<<EOF
EOF;
		return $BWHTML;
	}

	function addJavaScriptFile($file="",$type='file') {
		global $bw;
		$BWHTML .= <<<EOF
    <if="$type=='cur_file'">
		<script type="text/javascript" src='{$bw->vars['cur_scripts']}/{$file}.js'></script>
		<else />
		<if="$type=='external'">
			<script type="text/javascript" src='{$file}'></script>
			<else />
			<if="$type=='file'">
				<script type="text/javascript" src='{$bw->vars['board_url']}/javascripts/{$file}.js'></script>
			</if>
		</if>
	</if>

EOF;
		return $BWHTML;
	}

	function addJavaScript($script="") {
		$BWHTML = "";
		$BWHTML .= <<<EOF
<script language="javascript" type="text/javascript">
		{$script}
</script>
EOF;
		return $BWHTML;
	}

	function addDropDownScript($id="") {
		$BWHTML = "";
		//--starthtml--//

		$BWHTML .= <<<EOF
ddsmoothmenu.init({
	mainmenuid: "{$id}", //Menu DIV id
	orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
	classname: 'ddsmoothmenu-v', //class added to menus outer DIV
	//customtheme: ["#804000", "#482400"],
	contentsource: "markup", //"markup" or ["container_id", "path_to_menu_file"]
})
EOF;

		//--endhtml--//
		return $BWHTML;
	}

	function PermissionDenied($error="") {
		$BWHTML .= <<<EOF
<div class="red">
		{$error}</div>
EOF;
		return $BWHTML;
	}

	function displayFatalError($message="",$line="",$file="", $trace="") {
		$BWHTML .= <<<EOF
<div class="vs-common">
	<div class="red" align="left" style="padding: 20px">
		Error: {$message}<br />
		Line: {$line}<br />
		File: {$file}<br />
		Trace: <pre>{$trace}</pre><br />
	</div>
</div>
EOF;
		return $BWHTML;
	}
	function global_main_title() {
		global $bw, $vsPrint;
		$BWHTML = "";
		//--starthtml--//
		$BWHTML .= <<<EOF
	<span class="{$bw->input['module']}">{$vsPrint->mainTitle}</span>
EOF;

		//--endhtml--//
		return $BWHTML;
	}

	//===========================================================================
	// pop_up_window
	//===========================================================================
	function pop_up_window($title="",$css="",$text="") {
		$IPBHTML = "";
		//--starthtml--//


		$IPBHTML .= <<<EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xml:lang="en" lang="en" xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv="content-type" content="text/html; utf-8" />
  <title>$title</title>
  $css
 </head>
 <body>
 <div style='text-align:left'>
 $text
 </div>

 </body>
</html>
EOF;

 //--endhtml--//
 return $IPBHTML;
	}

	//===========================================================================
	// Redirect
	//===========================================================================
	function Redirect($Text="",$Url="",$css="") {
		global $bw;
		$BWHTML = "";
		//--starthtml--//
		//
		$BWHTML .= <<<EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/html40/loose.dtd">
<html>
	<head>
	<title>Redirecting...</title>
	<meta http-equiv='refresh' content='2; url=$Url' />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	$css
	<style type="text/css">
		.title
		{
			color:red;
		}
		.text
		{
			padding:10px;
			color:#009F3C;
		}
	</style>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-39253893-5', 'shophoa360.com');
  ga('send', 'pageview');

</script>
	</head>
  	<body >
		<center>
		<table style="background-color:#6ac3cb" cellpadding="0" cellspacing="0" width="100%" height="100%">
			<tr>
				<td width="416px" align="center" valign="middle" style="background:url({$bw->vars ['board_url']}/styles/redirect/direct.jpg) no-repeat center  top;" height="432px">
						<br/><br/><br/><br/>
					<img src="{$bw->vars ['board_url']}/styles/redirect/turtle.gif">
					<br/><br/>
					<p class="text">{$Text}</p>
				    <a href='$Url' title="{$Url}" class="title">( Click here if you do not wish to wait )</a>
				 </td>
			</tr>
		</table>
		</center>
	</body>
</html>
EOF;


	//--endhtml--//
	return $BWHTML;
	}

}

?>
